services:
  redy-blog-next:
    container_name: redy-blog-ui
    build:
      context: ./blog-frontend
      args:
        - UI_PORT=${UI_PORT}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - NEXT_INTERNAL_API_URL=${NEXT_INTERNAL_API_URL}
    depends_on:
      - redy-blog-api
    ports:
      - ${UI_PORT}:${UI_PORT}

  redy-blog-api:
    container_name: redy-blog-api
    build:
      context: ./blog-backend
    depends_on:
      - postgres
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      API_PATH: ${API_PATH}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  postgres:
    container_name: app_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}
